DELETE FROM CLASS;
INSERT INTO CLASS VALUES(1, 'ビール');
INSERT INTO CLASS VALUES(2, 'チューハイ');
INSERT INTO CLASS VALUES(3, 'ワイン');
INSERT INTO CLASS VALUES(4, '日本酒');
INSERT INTO CLASS VALUES(5, 'ウィスキー');

DELETE FROM MAKER;
INSERT INTO MAKER VALUES(1, '会社A');
INSERT INTO MAKER VALUES(2, '会社B');
INSERT INTO MAKER VALUES(3, '会社C');
INSERT INTO MAKER VALUES(4, '会社D');
INSERT INTO MAKER VALUES(5, '会社E');

DELETE FROM GOODS;
INSERT INTO GOODS VALUES(1, 'ビールA', 1, 1, 100, 80.5, 1000, 'test1', current_timestamp, 1);
INSERT INTO GOODS VALUES(2, 'チューハイB', 2, 2, 1200, 1000, 20000, 'test2', current_timestamp, 1);
INSERT INTO GOODS VALUES(3, 'ワインC', 3, 3, 10500, 9800, 300000, 'test3', current_timestamp, 1);
INSERT INTO GOODS VALUES(4, '日本酒D', 4, 4, 50, 10.1, 100, 'test4', current_timestamp, 1);